# Generated by Django 5.1.3 on 2024-12-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file_png',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='maskimage',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
