# Generated by Django 5.1.3 on 2024-11-18 20:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationcode',
            name='code',
            field=models.CharField(default=users.models.generate_code, editable=False, max_length=6, unique=True),
        ),
    ]
