version: '3.9'

networks:
  dev:

services:
  backend:
    build:
      context: ./backend
    env_file: ./backend/.env
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/web_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - dev

  celery:
    build:
      context: ./backend
    container_name: celery_worker
    command: celery -A core worker --pool=solo --loglevel=info
    volumes:
      - ./backend/web_service:/app
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - dev
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./backend/.env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - dev
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - dev

  nginx:
    build:
      context: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./backend/web_service/images:/app/images

    networks:
    - dev

volumes:
  postgres_data:
